name: mm-ci

on:
  pull_request:
  push:
    branches:
      - mm-new
      - mm-unstable
  workflow_dispatch:

jobs:
  host-tests:
    runs-on: self-hosted

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Run memblock tests
        run: bash .github/scripts/run-memblock-tests.sh

      - name: Run VMA tests
        if: always()
        run: bash .github/scripts/run-vma-tests.sh

      - name: Run data structure tests
        if: always()
        run: bash .github/scripts/run-datastructure-tests.sh

  vm-tests:
    runs-on: self-hosted

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Run VM tests
        run: bash .github/scripts/run-vm-tests.sh
